# Generated by Django 4.2.30 on 2026-05-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalitem',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='Площадь (м²)'),
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Квартира'), ('house', 'Дом'), ('room', 'Комната'), ('office', 'Офис'), ('garage', 'Гараж'), ('other', 'Другое')], default='apartment', max_length=20, verbose_name='Тип недвижимости'),
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='rooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество комнат'),
        ),
    ]
